# Generated by Django 5.1.2 on 2024-10-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodeorden',
            options={'verbose_name': 'Tipo de orden', 'verbose_name_plural': 'Tipo de orden'},
        ),
    ]
