# Generated by Django 5.1.2 on 2024-10-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NombreIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NombreReceta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_de_orden', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de orden',
                'verbose_name_plural': 'Tipo de orden',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.CharField(max_length=255)),
                ('nombre_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nombreingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('nombre_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nombrereceta')),
                ('receta_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recetaingrediente')),
            ],
            options={
                'verbose_name': 'Recetas',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('hash_pass', models.CharField(max_length=45)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('receta_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recetapedido')),
                ('tipo_de_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodeorden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
