# Generated by Django 5.1.2 on 2024-10-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
