# Generated by Django 5.1.3 on 2024-11-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingrediente_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='link',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_recetas/'),
        ),
    ]
