# Generated by Django 5.1.2 on 2024-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipodeorden_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetas',
            options={'verbose_name': 'Recetas', 'verbose_name_plural': 'Recetas'},
        ),
    ]
