# Generated by Django 5.1.3 on 2024-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recetas_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
