# Generated by Django 5.1.3 on 2024-12-12 01:49

from django.db import migrations, connection # type: ignore

def reset_auto_increment(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE core_ingrediente AUTO_INCREMENT = 1;")
        
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recetamodificada_pedido_receta_modificada'),
    ]

    operations = [
        migrations.RunPython(reset_auto_increment),
    ]
