# Generated by Django 5.1.3 on 2024-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241211_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='pais',
            field=models.CharField(default='Chile', max_length=255),
        ),
        migrations.AddField(
            model_name='recetas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='recetas',
            name='tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
